# Generated by Django 4.2 on 2023-04-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_people'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='people',
            new_name='leads',
        ),
    ]
